### ISSUE TITLE
Matcher for part of object properties

### ISSUE THREAD

**Issue by krzysztof-jelski** [earl-js/earl#63] opened 2020-11-19 08:32 UTC
It'd be cool to have a matcher for a subset of object properties. Eg.:

`expect({a: 1, b: 2, c: 3}).toContainSubset({a: 1, c: 3})`

**Comment by krzkaczor** [comment] 2020-11-19 09:26
We already have `expect.containerWith` for iterables and we still need `arrayWith` and `objectWith`.

This is tracked in: https://github.com/earl-js/earl/issues/48 so I'll close this as a duplicate.

It will be done during the weekend by me but you can contribute it if you want earlier :-> It's a simple matcher and we have already similar ones.

**Comment by sz-piotr** [comment] 2020-11-19 10:33
Why close this? The issue is about a validator, not a matcher (even though the name matcher is used)

**Comment by krzkaczor** [comment] 2020-11-19 10:42
Uhh, I thought it's about matchers. Linking to our docs for completeness: https://earljs.dev/docs/introduction/core-concepts

Still, my thinking is that we don't need validators duplicating what can be easily achieved with existing validators + matchers. For example:

```typescript
expect({a: 1, b: 2, c: 3}).toContainSubset({a: 1, c: 3})
```

Is the same as:

```typescript
expect({a: 1, b: 2, c: 3}).toEqual(expect.objectWith({a: 1, c: 3}))
```

Matchers are in principle more powerful than validators as they can be used in many different contexts (for example in `given` of mocks) and they compose well.

I don't have a very strong opinion on this as I already saw with `toThrow` that it's not always a good idea to embrace matchers 😆 But if we decide to introduce these validators, their naming should be inlined with matchers to make it clear that it's a shorthand.

I'll reopen to discuss.

**Comment by sz-piotr** [comment] 2020-11-22 11:42
Personally i believe it is good to have duplication in this particular case. Possibly also with `expect.a` we could have `expect(x).toBeA` validator.

All in all it comes down to the fact that the code should be the most descriptive, since the tests serve as specification. So it is more descriptive to write `expect([1, 2]).toContain(1)` than `expect([1, 2]).toEqual(expect.arrayWith(1))`. The second, while more powerful introduces a lot of noise, potentially leading to people thinking functionality like this is missing.

**Comment by krzkaczor** [comment] 2020-12-03 21:05
Okay I agree that these validators would be handy indeed. Lets start with:

- `expect(x).toBeA(...)` uses `expect.a`
- `expect(x).toBeContainerWith` uses `expect.containerWith`
- `expect(x).toBeArrayWith` uses `expect.arrayWith`
- `expect(x).toBeObjectWith` uses `expect.objectWith`

Note: I renamed `toContainSubset` proposed in by @krzysztof-jelski to something that goes well with the names that we picked for matchers.

Let me know if you have any naming suggestions.

**Comment by krzysztof-jelski** [comment] 2020-12-03 21:06
Yes, the naming looks perfect 👌

**Comment by krzysztof-jelski** [comment] 2020-12-03 21:11
Hmm perhaps grammar-wise we should add an indefinite article in each one, as in:

`expect(x).toBeAnObjectWith`

**Comment by krzkaczor** [comment] 2020-12-03 21:13
Yeah, I wondered about this too. I will check how other libs go about it, after all, we don't have `expect.a.objectWith()` 🤷

**Comment by krzkaczor** [comment] 2020-12-05 15:52
@all-contributors please add @krzysztof-jelski for ideas

**Comment by krzkaczor** [comment] 2020-12-05 15:53
@sz-piotr do you have any opinions on naming here?

**Comment by sz-piotr** [comment] 2020-12-05 19:56
I'd prefer something grammatically correct. So definitely `toBeAContainerWith` and `toBeAnArrayWith` over `toBeContainerWith` and `toBeArrayWith`. I'd also propose renaming `toBeAContainerWith` to `toContain`

**Closed** 2020-12-15 18:30 UTC
Labels: good first issue, help wanted

**Comment by krzkaczor** [comment] 2020-12-15 18:35
@all-contributors please add @krzysztof-jelski for ideas
